---

# NOTE: Do not use easy_install for RedHat. There is a bug that might cause
# easy_install to hang:
# https://github.com/ansible/ansible/issues/15769
# https://bugzilla.redhat.com/show_bug.cgi?id=1702797
# Use shell to intall pip for RedHat to work around the bug

- name: check if pip present
  shell: python3 -m pip --version
  ignore_errors: true
  register: pip_check

- name: Install pip
  block:
    - name: Download pip
      get_url:
        url: "{{ get_pip_url }}"
        dest: /tmp/get-pip.py
        force: yes
        mode: 0400
    - name: Install pip
      shell: "python3 /tmp/get-pip.py"
      become: yes
  when:
    - pip_check.rc != 0

# if pip was already there then it should be updated if it's version is less than 10.0
# (it doesn't support python2/3 metadata)
- name: upgrade pip
  shell: python3 -m pip install --upgrade 'pip>=20'
  become: yes
  register: res
  retries: 5
  until: res is success
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1
  when:
    - ansible_distribution != 'Ubuntu' or ansible_distribution_version != '24.04'
