---

default_openstack_version: rocky
openstack_version: >-
    {%- if contrail_configuration.OPENSTACK_VERSION is defined -%}
      {{ contrail_configuration.OPENSTACK_VERSION }}
    {%- elif kolla_config.kolla_globals is defined and kolla_config.kolla_globals.openstack_release is defined -%}
      {{ kolla_config.kolla_globals.openstack_release }}
    {%- else -%}
      {{ default_openstack_version }}
    {%- endif %}
