supported_orchestrators:
  - openstack
  - kubernetes
  - none
contrail_configuration_keystone_default:
  KEYSTONE_AUTH_ADMIN_TENANT: admin
  KEYSTONE_AUTH_ADMIN_USER: admin
opencontrail_api_server_ip: "{{ contrail_configuration.CONFIG_NODES | default(contrail_configuration.CONTROLLER_NODES | default(config_nodes_list | join(','))) | replace (',', ' ') }}"
opencontrail_collector_ip: "{{ contrail_configuration.ANALYTICS_NODES | default(contrail_configuration.CONTROLLER_NODES | default(analytics_nodes_list | join(','))) | replace (',', ' ') }}"
KEYSTONE_AUTH_PROTO: http
KEYSTONE_AUTH_PUBLIC_PORT: 5000
ANALYTICS_API_PORT: 8081
CONFIG_API_PORT: 8082
default_openstack_version: yoga
openstack_version: >-
    {%- if contrail_configuration.OPENSTACK_VERSION is defined -%}
      {{ contrail_configuration.OPENSTACK_VERSION }}
    {%- elif kolla_config.kolla_globals is defined and kolla_config.kolla_globals.openstack_release is defined -%}
      {{ kolla_config.kolla_globals.openstack_release }}
    {%- else -%}
      {{ default_openstack_version }}
    {%- endif %}
