---
- name: OS specific package install
  include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- name: install git to operate on kolla branches
  package:
    name: git
    state: present
  become: yes
