---

- name: split k8s_version by dots
  set_fact:
    k8s_repo_version: "{{ k8s_version.split('.') }}"

- name: add k8s repo key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: k8s_package_version is defined

- name: create k8s repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_repo_version[0] }}.{{ k8s_repo_version[1] }}/deb/ /"
    state: present
  when: k8s_package_version is defined
